import Mathlib.Analysis.Calculus.ContDiff.Operations
import Mathlib.Algebra.Lie.OfAssociative
import Mathlib.Algebra.Lie.Subalgebra
import Mathlib.Algebra.MvPolynomial.Degrees
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.Tactic.Ring

/-!
# The original smooth Wong-matrix problem: a statement, not a proof

The state space is real three-space. Operators act on actual globally smooth
real functions. In particular, differentiation is made linear only after
restricting to smooth inputs. The estimation algebra is the actual Lie
subalgebra generated by the filtering operator and observation multipliers.

`mainClaim` below is a definition of the proposition to be proved. There is
no theorem asserting it, no additional axiom, and no placeholder proof.
-/

noncomputable section
namespace Wong.SmoothModel
open scoped ContDiff

abbrev State := Fin 3 → ℝ

/-- Globally smooth functions, as a real vector subspace of all functions. -/
def smoothSpace : Submodule ℝ (State → ℝ) where
  carrier := {u | ContDiff ℝ ∞ u}
  zero_mem' := by
    change ContDiff ℝ ∞ (fun _ : State => (0 : ℝ))
    exact contDiff_const
  add_mem' := by
    intro u v hu hv
    change ContDiff ℝ ∞ u at hu
    change ContDiff ℝ ∞ v at hv
    change ContDiff ℝ ∞ (u + v)
    exact hu.add hv
  smul_mem' := by
    intro c u hu
    change ContDiff ℝ ∞ u at hu
    change ContDiff ℝ ∞ (fun x => c * u x)
    exact contDiff_const.mul hu

abbrev Smooth := ↥smoothSpace
abbrev Operator := Module.End ℝ Smooth

theorem smooth (u : Smooth) : ContDiff ℝ ∞ u.1 := u.property

instance : LieRing Operator := LieRing.ofAssociativeRing
instance : LieAlgebra ℝ Operator := LieAlgebra.ofAssociativeAlgebra

/-- The ordinary coordinate vector in real three-space. -/
def coordinateVector (i : Fin 3) : State := Pi.single i 1

/-- Genuine coordinate differentiation on globally smooth functions. -/
def partialDerivative (i : Fin 3) : Operator where
  toFun u := ⟨fun x => fderiv ℝ u.1 x (coordinateVector i),
    ((contDiff_infty_iff_fderiv.mp (smooth u)).2).clm_apply contDiff_const⟩
  map_add' u v := by
    apply Subtype.ext
    funext x
    change fderiv ℝ (u.1 + v.1) x (coordinateVector i) = _
    rw [fderiv_add
      (((smooth u).differentiable (by simp)).differentiableAt)
      (((smooth v).differentiable (by simp)).differentiableAt)]
    rfl
  map_smul' c u := by
    apply Subtype.ext
    funext x
    change fderiv ℝ (c • u.1) x (coordinateVector i) = _
    rw [fderiv_const_smul
      (((smooth u).differentiable (by simp)).differentiableAt) c]
    rfl

/-- Pointwise multiplication preserves global smoothness. -/
def smoothMul (u v : Smooth) : Smooth :=
  ⟨fun x => u.1 x * v.1 x, (smooth u).mul (smooth v)⟩

/-- The actual multiplication operator by a smooth scalar function. -/
def multiplication (u : Smooth) : Operator where
  toFun := smoothMul u
  map_add' v w := by
    apply Subtype.ext
    funext x
    exact mul_add (u.1 x) (v.1 x) (w.1 x)
  map_smul' c v := by
    apply Subtype.ext
    funext x
    change u.1 x * (c * v.1 x) = c * (u.1 x * v.1 x)
    ring

/-- The covariant derivative `D_i = ∂_i - f_i`. -/
def D (f : Fin 3 → Smooth) (i : Fin 3) : Operator :=
  partialDerivative i - multiplication (f i)

/-- The original filtering potential, including all observation squares. -/
def eta {m : ℕ} (f : Fin 3 → Smooth) (h : Fin m → Smooth) : Smooth :=
  (∑ i, ((partialDerivative i) (f i) + smoothMul (f i) (f i))) +
    ∑ j, smoothMul (h j) (h j)

/-- The filtering generator for orthogonal diffusion, whose covariance is
    the identity: `L₀ = 1/2 ∑ D_i² - 1/2 η`. -/
def L0 {m : ℕ} (f : Fin 3 → Smooth) (h : Fin m → Smooth) : Operator :=
  (1 / 2 : ℝ) • (∑ i, D f i * D f i) -
    (1 / 2 : ℝ) • multiplication (eta f h)

/-- The least real Lie subalgebra containing the actual generators. -/
def estimationAlgebra {m : ℕ} (f : Fin 3 → Smooth) (h : Fin m → Smooth) :
    LieSubalgebra ℝ Operator :=
  LieSubalgebra.lieSpan ℝ Operator ({L0 f h} ∪ Set.range (fun j => multiplication (h j)))

/-- The homogeneous linear scalar function with coefficient vector `a`. -/
def linearFunction (a : State) : Smooth :=
  ⟨fun x => ∑ i, a i * x i, by
    change ContDiff ℝ ∞ (fun x : State => ∑ i, a i * x i)
    apply ContDiff.sum
    intro i _
    exact contDiff_const.mul (ContinuousLinearMap.proj i : State →L[ℝ] ℝ).contDiff⟩

/-- Homogeneous linear multiplication operators, parametrized linearly by
    their three real coefficients. -/
def linearMultiplication : State →ₗ[ℝ] Operator where
  toFun a := multiplication (linearFunction a)
  map_add' a b := by
    apply LinearMap.ext
    intro u
    apply Subtype.ext
    funext x
    change (∑ i, (a i + b i) * x i) * u.1 x =
      (∑ i, a i * x i) * u.1 x + (∑ i, b i * x i) * u.1 x
    simp only [add_mul, Finset.sum_add_distrib]
  map_smul' c a := by
    apply LinearMap.ext
    intro u
    apply Subtype.ext
    funext x
    change (∑ i, (c * a i) * x i) * u.1 x =
      c * ((∑ i, a i * x i) * u.1 x)
    simp only [mul_assoc, ← Finset.mul_sum]

/-- The constant one is an actual smooth test function. -/
def smoothOne : Smooth := ⟨fun _ => 1, by
  change ContDiff ℝ ∞ (fun _ : State => (1 : ℝ))
  exact contDiff_const⟩

/-- Coefficient vectors identify distinct linear multiplication operators.
    Thus the coefficient-space definition does not collapse the linear rank. -/
theorem linearMultiplication_injective : Function.Injective linearMultiplication := by
  intro a b hab
  funext i
  have he := congrArg (fun A : Operator => (A smoothOne).1 (coordinateVector i)) hab
  simpa [linearMultiplication, multiplication, smoothMul, linearFunction,
    smoothOne, coordinateVector, Pi.single_apply, mul_ite] using he

/-- Coefficients of precisely those homogeneous linear multipliers lying
    in `E`; no adapted-coordinate assumption has been inserted. -/
def linearCoefficientSpace (E : LieSubalgebra ℝ Operator) : Submodule ℝ State :=
  E.toSubmodule.comap linearMultiplication

/-- Linear rank in the manuscript's original homogeneous-linear convention. -/
def linearRank (E : LieSubalgebra ℝ Operator) : ℕ :=
  Module.finrank ℝ (linearCoefficientSpace E)

/-- No polynomial multiplication operator of total degree exactly two lies
    in the algebra. The action is specified pointwise, so this definition
    does not require an arbitrary chosen smoothness witness for a polynomial. -/
def QuadraticFree (E : LieSubalgebra ℝ Operator) : Prop :=
  ∀ p : MvPolynomial (Fin 3) ℝ, p.totalDegree = 2 →
    ¬ ∃ A : Operator, A ∈ E ∧
      ∀ (u : Smooth) (x : State), (A u).1 x = MvPolynomial.eval x p * u.1 x

/-- The actual Wong matrix entries `ω_ij = ∂_i f_j - ∂_j f_i`. -/
def wong (f : Fin 3 → Smooth) (i j : Fin 3) : Smooth :=
  (partialDerivative i) (f j) - (partialDerivative j) (f i)

/-- Constancy concerns the Wong matrix, not the Lie algebra as an object. -/
def WongConstant (f : Fin 3 → Smooth) : Prop :=
  ∃ Ω : Fin 3 → Fin 3 → ℝ,
    ∀ (i j : Fin 3) (x : State), (wong f i j).1 x = Ω i j

/-- The conditional intermediate used by the slope-elimination proof.
    Quadratic-freeness is derived separately before applying this result. -/
def QuadraticFreeMainClaim : Prop :=
  ∀ (m : ℕ) (f : Fin 3 → Smooth) (h : Fin m → Smooth),
    FiniteDimensional ℝ (estimationAlgebra f h) →
    linearRank (estimationAlgebra f h) = 2 →
    QuadraticFree (estimationAlgebra f h) → WongConstant f

/-- The paper's main claim for the actual smooth filtering model:
    finite-dimensionality and linear rank two imply a constant Wong matrix.
    There is no quadratic-freeness hypothesis. -/
def mainClaim : Prop :=
  ∀ (m : ℕ) (f : Fin 3 → Smooth) (h : Fin m → Smooth),
    FiniteDimensional ℝ (estimationAlgebra f h) →
    linearRank (estimationAlgebra f h) = 2 → WongConstant f

end Wong.SmoothModel
