import Wong.PolynomialVisibleDerivativeBridge
import Wong.FirstOrderNormalBridge

/-!
# Genuine first-order operators under admitted visible commutators

The zero-order remainder is generated by actual Lie brackets at every step.
No multiplication closure of the estimation algebra, hidden covariant
derivative membership, or removal of a variable visible coefficient is used.
-/

noncomputable section
set_option autoImplicit false
namespace Wong.SmoothModel
open MvPolynomial

theorem firstOrder_partial_powers_mem {m : ℕ}
    (f : Fin 3 → Smooth) (h : Fin m → Smooth) (i : Fin 3)
    (hi : D f i ∈ estimationAlgebra f h)
    (a : Fin 3 → Smooth) (b : Smooth)
    (hab : firstOrder f a b ∈ estimationAlgebra f h) (n : ℕ) :
    ∃ c : Smooth, firstOrder f (fun j => (partialDerivative i ^ n) (a j)) c ∈
      estimationAlgebra f h := by
  induction n with
  | zero => exact ⟨b, by simpa using hab⟩
  | succ n ih =>
    obtain ⟨c, hc⟩ := ih
    have hb := (estimationAlgebra f h).lie_mem hi hc
    rw [lie_D_firstOrder] at hb
    refine ⟨partialDerivative i c +
      ∑ j, smoothMul ((partialDerivative i ^ n) (a j)) (wong f j i), ?_⟩
    simpa only [Wong.AdjointIteration.end_pow_succ_apply] using hb

theorem firstOrder_visible_partial_powers_mem {m : ℕ}
    (f : Fin 3 → Smooth) (h : Fin m → Smooth)
    (hD₀ : D f 0 ∈ estimationAlgebra f h) (hD₁ : D f 1 ∈ estimationAlgebra f h)
    (a : Fin 3 → Smooth) (b : Smooth)
    (hab : firstOrder f a b ∈ estimationAlgebra f h) (r s : ℕ) :
    ∃ c : Smooth,
      firstOrder f (fun j => (partialDerivative 0 ^ r) ((partialDerivative 1 ^ s) (a j))) c ∈
        estimationAlgebra f h := by
  obtain ⟨c₁, hc₁⟩ := firstOrder_partial_powers_mem f h 1 hD₁ a b hab s
  exact firstOrder_partial_powers_mem f h 0 hD₀ _ c₁ hc₁ r

theorem firstOrder_visible_polynomial_derivatives_mem {m : ℕ}
    (f : Fin 3 → Smooth) (h : Fin m → Smooth)
    (hD₀ : D f 0 ∈ estimationAlgebra f h) (hD₁ : D f 1 ∈ estimationAlgebra f h)
    (P : Fin 3 → RealPoly) (b : Smooth)
    (hP : firstOrder f (fun j => polynomialSmooth (P j)) b ∈ estimationAlgebra f h)
    (r s : ℕ) :
    ∃ c : Smooth,
      firstOrder f (fun j => polynomialSmooth (visiblePolynomialDerivative r s (P j))) c ∈
        estimationAlgebra f h := by
  obtain ⟨c, hc⟩ := firstOrder_visible_partial_powers_mem f h hD₀ hD₁ _ b hP r s
  exact ⟨c, by simpa only [polynomialSmooth_visiblePolynomialDerivative] using hc⟩

end Wong.SmoothModel

#print axioms Wong.SmoothModel.firstOrder_visible_polynomial_derivatives_mem
