name = "wong_audit"
version = "0.1.0"
defaultTargets = ["Wong"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc2"

[[require]]
name = "plausible"
scope = "leanprover-community"

[[require]]
name = "importGraph"
scope = "leanprover-community"

[[require]]
name = "LeanSearchClient"
scope = "leanprover-community"

[[require]]
name = "proofwidgets"
scope = "leanprover-community"

[[require]]
name = "aesop"
scope = "leanprover-community"

[[require]]
name = "Qq"
scope = "leanprover-community"

[[require]]
name = "batteries"
scope = "leanprover-community"

[[require]]
name = "Cli"
scope = "leanprover"

[[lean_lib]]
name = "Wong"
